### test a http request
POST http://localhost:8081/
Content-Type: application/json

{
  "method": "createObjectWithText",
  "args": [
    ["1"], "some test text"
  ]
}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Response content-type is json", function () {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", `Expected 'application/json' but received '${type}'`);
    });
    client.test("Response contains a name", function () {
        client.assert(response.body.match(/^[0-9a-zA-Z]{5,20}$/), 'Expected an alphanumeric string longer than 5, but received: ' + response.body);
    });
%}